### ISSUE TITLE
应用内存占用问题

### ISSUE THREAD

**Issue by czj-dev** [CodeCrafts-app/CodeCrafts#1]
为什么这个 App 在使用了一段时间后直接内存空间占用了上百GB？

**Comment by CodeCrafts-app** [comment]
有两个可能
1. 你的logcat日志太多
2. bugreport占用太多空间

可以先尝试在logcat记录和anr记录里面清理掉日志

我记录下来后面优化一下

**Comment by czj-dev** [comment]
好的，应该是一直记录 logcat 导致。感谢解答
