### ISSUE TITLE
打开悬浮窗应用崩溃

### ISSUE THREAD

**Issue by NanyangLi** [CodeCrafts-app/CodeCrafts#2]
环境信息:
机型:魅族18s Pro
Flyme:9.3.1.0A

堆栈:
04-13 16:46:22.396 29654 29654 D AndroidRuntime: Shutting down VM
04-13 16:46:22.396 29654 29654 E AndroidRuntime: FATAL EXCEPTION: main
04-13 16:46:22.396 29654 29654 E AndroidRuntime: Process: com.luqinx.devkits.codecrafts, PID: 29654
04-13 16:46:22.396 29654 29654 E AndroidRuntime: java.lang.ClassCastException: android.app.AppOpsManager cannot be cast to a.a
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at e6.a.c(FloatingWindowPermissionUtils.kt:1)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at e6.a.a(FloatingWindowPermissionUtils.kt:29)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at k5.q.f(FloatingBarWindow.kt:2)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at com.huawei.agconnect.common.api.f.a(R8$$SyntheticClass:3)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at androidx.preference.Preference.r(Unknown Source:4)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at androidx.preference.TwoStatePreference.I(TwoStatePreference.java:2)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at androidx.preference.Preference.P(Preference.java:2)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at androidx.preference.SwitchPreferenceCompat.P(SwitchPreferenceCompat.java:1)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at androidx.preference.Preference$a.onClick(Unknown Source:2)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at android.view.View.performClick(View.java:7464)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7441)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at android.view.View.access$3600(View.java:823)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28382)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7822)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-13 16:46:22.396 29654 29654 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
04-13 16:46:23.341 30235 30235 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.

**Comment by NanyangLi** [comment]
codecrafts 版本: 1.0.15

**Comment by luqinx** [comment]
fixed on 1.0.18
